update_fastlane

default_platform(:android)


  desc "Upload apk to App Center"
  lane :upload do

  appcenter_upload(
    api_token: ENV["APP_CENTER_API_TOKEN"],
    owner_name: "rodrigo.m",
    destinations: "noobs",
    app_name: "NarutoArena",
    apk: "app/build/outputs/apk/dev/release/app-dev-arm64-v8a-release.apk",
    app_os: 'Android',
    notify_testers: true 
  )

  end


  desc "Bundle release app"
  lane :beta do

    # changelog_from_git_commits
    
    begin

      gradle(task: "clean assembleRelease")

    rescue => ex

      raise ex

      UI.important("Deu merda no build mermão",ex.message)
    end

    upload
  end
