update_fastlane

default_platform(:android)

desc "Bump patch"
  lane :version_patch do 
    gradle(task: 'bumperVersionPatch')
  end

desc "Bump minor"
  lane :version_minor do 
    gradle(task: 'bumperVersionMinor')
  end

  desc "Upload apk to App Center"
  lane :upload do

  UI.message("\n\n\n=====================================\n uploading android\n=====================================")
  
   notes = File.read('./release-notes.md') 

  appcenter_upload(
    api_token: ENV["APP_CENTER_API_TOKEN"],
    owner_name: "rodrigo.m",
    destinations: "noobs",
    app_name: "NarutoArena",
    apk: "app/build/outputs/apk/dev/release/app-dev-arm64-v8a-release.apk",
    app_os: 'Android',
    notify_testers: true,
    release_notes: notes
  )

  end

  desc "Bundle release app"
  lane :deploy do

    # changelog_from_git_commits
    version_patch 
    
    begin

      gradle(task: "clean assembleRelease")

    rescue => ex

      raise ex

      UI.important("Deu merda no build mermão",ex.message)
    end

    upload
  end
